root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
bin = "tmp/main"
full_bin = "tmp/main"
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_ext = ["tmp", "vendor"]

[log]
time = true

[color]
main = "yellow"
watcher = "green"
build = "cyan"